name: Cancel on Custom AsciiDoc Conversion
on:
  workflow_run:
    workflows: ["Custom AsciiDoc Conversion"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.9.1
      with:
        workflow_id: ${{ github.event.workflow.id }}
